#!/bin/bash

source ./set-env.sh

set -e

if [ "$NGINX_VERSION" == "" ]; then
  echo "must set NGINX_VERSION, i.e NGINX_VERSION=1.2.0"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

if [ -z "$NGINX_ZLIB_VERSION" ]; then
    NGINX_ZLIB_VERSION=1.2.8
fi

zlib_version="$NGINX_ZLIB_VERSION"

# make a temp directory
tempdir="$( mktemp -t nginx_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract nginx
curl -L http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o - | tar xz

# download and extract pcre into contrib directory
mkdir -p $tempdir/contrib
pushd $tempdir/contrib
wget http://downloads.sourceforge.net/project/pcre/pcre/8.21/pcre-8.21.tar.gz
tar xz pcre-8.21.tar
rm pcre-8.21.tar.gz
popd

# download and extract zlib into contrib directory
mkdir -p $tempdir/zlib
pushd $tempdir/zlib
wget http://s3.amazonaws.com/s3.hmt.fm/cedar14/zlib-1.2.8.tar.gz
tar xz zlib-1.2.8.tar.gz
rm zlib-1.2.8.tar.gz
popd

pushd $tempdir/nginx-$NGINX_VERSION

./configure --prefix=$tempdir/build --with-pcre=$tempdir/contrib/pcre-8.21 --with-zlib=$tempdir/zlib/zlib-1.2.8 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module && make install

pushd $tempdir/build

tar czf /vagrant/_compiled/nginx-$NGINX_VERSION.tar.gz .

popd

echo "+ Binaries available at ./nginx-$NGINX_VERSION-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

# upload to s3
#s3cmd put -rr $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz s3://$S3_BUCKET
