#!/bin/bash

source ./set-env.sh

set -e

if [ "$NCAT_VERSION" == "" ]; then
  echo "must set NCAT_VERSION, i.e NCAT_VERSION=7.70"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t ncat_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract nginx
curl -L https://nmap.org/dist/nmap-$NCAT_VERSION.tgz -o - | tar xz

pushd $tempdir/nmap-$NCAT_VERSION

mkdir -p /app/vendor/nmap

./configure --prefix=/app/vendor/nmap && make && make install

pushd /app/vendor/nginx

tar czf /vagrant/_compiled/nmap-$NCAT_VERSION.tar.gz .

popd

echo "+ Binaries available at ./nmap-$NCAT_VERSION-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

