#!/bin/bash

source ./set-env.sh

set -e

if [ "$NGINX_VERSION" == "" ]; then
  echo "must set NGINX_VERSION, i.e NGINX_VERSION=1.2.0"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t nginx_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract nginx
curl -L http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o - | tar xz

# download and extract pcre into contrib directory
mkdir -p $tempdir/contrib
pushd $tempdir/contrib
wget http://downloads.sourceforge.net/project/pcre/pcre/8.21/pcre-8.21.tar.gz
gunzip pcre-8.21.tar.gz
tar -xvf pcre-8.21.tar
popd

# build and package nginx for heroku
#vulcan build -v -s nginx-$NGINX_VERSION -o $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz -p /app/vendor/nginx -c './configure --prefix=/app/vendor/nginx --with-pcre=contrib/pcre-8.21 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module && make install'

pushd $tempdir/nginx-$NGINX_VERSION

./configure --prefix=$tempdir/build --with-pcre=$tempdir/contrib/pcre-8.21 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module && make install

pushd $tempdir/build

tar czf /vagrant/_compiled/nginx-$NGINX_VERSION.tar.gz .

popd

#cp $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz .

echo "+ Binaries available at ./nginx-$NGINX_VERSION-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

# upload to s3
#s3cmd put -rr $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz s3://$S3_BUCKET
